### ISSUE TITLE
mps-all plugins incompatible with MPS 3.3.5

### ISSUE THREAD

**Issue by fac2003** [slisson/mps-all#5]
Same issue as when 3.3.4 was released.

**Comment by slisson** [comment]
We are not able to build mbeddr with MPS 3.3.5 at the moment.

**Comment by fac2003** [comment]
That's unfortunate. Thanks for letting me know.

**Comment by slisson** [comment]
The plugins you need are not affected. They are available now.

**Comment by fac2003** [comment]
Thanks!
